Installation
------------

Astive Toolkit is fast and easy to install. Astive Toolkit does not support a particular database, or logging platform, its up to you to decide the libraries suitable for your voice applications. Luckily, Apache Maven has a large collection of dependencies that you can use for those purposes. It does not require of any special configuration, just download and uncompress. The minimum requirements are:

- Java 6
- Maven 3.x.x.
- Asterisk 1.8 or greater,
- A copy of ATK

Having +git+ may become handy to test new features or get a bug fix. ATK may be able to function with older versions of Asterisk and Maven, that we have not tested. Should you test prior versions, we would love to hear about your experience. 

License
~~~~~~~

Astive Toolkit is licensed under the Apache License 2.0. This means that you are free to modify, distribute and republish the source code on the condition that the copyright notices are left intact. You are also free to incorporate Astive Toolkit into any Commercial or closed source application.

Downloading ATK
~~~~~~~~~~~~~~~

ATK consists in two main pieces, the Astive Server and the Development Kit. There are two main ways to get a fresh copy of ATK. You can either download the +tar.gz+ from the main website, or checkout the code from the git repository. To download the latest major release of Astive Toolkit. Visit the main website http://astivetoolkit.org and follow the download link.

All current releases of ATK are hosted on http://github.com/fonoster/astivetoolkit[Github]. Github houses both ATK itself as well as many other resources for Astive Toolkit. The ATK releases are available at Github tags (https://github.com/fonoster/astivetoolkit/tags). Alternatively you can get fresh off the press code, with all the bug fixes and up to the minute enhancements. 

These can be accessed from Github by cloning the following repository:

....
$ git clone git://github.com/fonoster/astivetoolkit.git
....

You will then need to assemble ATK by doing this:

....
$ cd astivetoolkit
$ ./assembly
....

NOTE: The assemblies of ATK can be found in *_dist_* folder.

Setting Up Astive Server
~~~~~~~~~~~~~~~~~~~~~~~~

Setting up Astive Server is really simple. Decompress the _astivetoolkit-server-1.x.x.tar.gz_ that you obtained in the previous section. To test your installation get the example application http://astivetoolkit.org/downloads[helloworld.jar]. Then, go to your the Astive Server folder and perform the following instruction:

....
$ ./bin/astived start -d
....

This is going to start Astive Server in debug mode. Open another console and execute

....
$ ./bin/astived deploy [the application path]/helloworld.jar
....

If you performed all the steps correctly your application is ready to receive incoming connections from your Asterisk system.

Installing the SDK
~~~~~~~~~~~~~~~~~~

To install the SDK decompress the file _astivetoolkit-sdk-1.x.x.tar.gz_ obtained in the Download ATK section of this chapter. Use the script *installSDK* to publish all the artifacts to your local maven repository.
