Getting Started
---------------

Astive Toolkit provides a robust base for your voice applications. It can handle every aspect of your project, from building the application up to deploy to production. And, since the toolkit follows principles similar to MVC, it allows you to easily customize, build and extend most aspects of your application.

The toolkit also provides a basic organizational structure, based on _Maven Archetypes_, keeping your entire application consistent and logical. This concept is simple but powerful. Follow the conventions and you will always know exactly where things are.

The best way to experience and learn Astive Toolkit is to sit down and build something. To start off, let's build the classic _"Hello World"_ application.

Installation
------------

Astive Toolkit is fast and easy to install. Astive Toolkit does not support a particular database, or logging platform, its up to you to decide the libraries suitable for your voice applications. Luckily, Apache Maven has a large collection of dependencies that you can use for those purposes. It does not require of any special configuration, just download and uncompress. The minimum requirements are:

- Java 6
- Maven 3.x.x.
- Asterisk 1.8 or greater,
- A copy of ATK

Having +git+ may become handy to test new features or get a bug fix. ATK may be able to function with older versions of Asterisk and Maven, that we have not tested. Should you test prior versions, we would love to hear about your experience.

License
~~~~~~~

Astive is licensed under the Apache License 2.0. This means that you are free to modify, distribute and republish the source code on the condition that the copyright notices are left intact. You are also free to incorporate Astive Toolkit into any Commercial or closed source application.

Downloading Astive
~~~~~~~~~~~~~~~

Astive consists in two main pieces, the Astive Server and the Development Kit. There are two main ways to get a fresh copy of Astive. You can either download the +tar.gz+ from github releases, or checkout the code from the git repository.

Current releases of Astive are hosted on http://github.com/fonoster/astive[Github]. Github houses both ATK itself as well as many other resources for Astive. The ATK releases are available at Github tags (https://github.com/fonoster/astive/tags). Alternatively you can get fresh off the press code, with all the bug fixes and up to the minute enhancements.

These can be accessed from Github by cloning the following repository:

....
$ git clone git://github.com/fonoster/astive.git
....

You will then need to assemble Astive by doing this:

....
$ cd astive
$ ./assembly
....

NOTE: The assemblies of ATK can be found in *_dist_* folder.

Setting Up Astive Server
~~~~~~~~~~~~~~~~~~~~~~~~

Setting up Astive Server is really simple. Decompress the _astive-server-1.x.x.tar.gz_ that you obtained in the previous section. 

....
$ ./bin/astived start -d
....

This is going to start Astive Server in debug mode. Open another console and execute

....
$ ./bin/astived deploy [the application path]/helloworld.jar
....

If you performed all the steps correctly your application is ready to receive incoming connections from your Asterisk system.
