Astive Overview
------------

Welcome to the Astive Developer Guide. This manual has been created to assist you in developing voice applications with Astive Toolkit.

This manual assumes that you possess a general understanding of Java and a basic understanding of object oriented programming (OOP) as well as the basic aspects of configuring the Asterisk PBX. Functionalities within the framework structure make use of different technologies – such as XML, Asterisk – and this manual does not focus in describe those technologies, except for the role they play in context.

*What is Astive? Why Use it?*

Astive is a free, open-source, rapid development framework for Java. Its a foundational format for programmers to create voice applications. Our primary goal is to allow you to work in a structured and rapid manner–without losing of flexibility. It's a set of apis and server that aim to make voice application easy.

Astive takes the complexity out of voice development; providing you with all the necessary tools to get started coding what you need to get done: the logic specific to your application. You won't have to reinvent the wheel every time you sit down to a new project, just generate a skeleton with _archetypes_ and get ready to code.

In addition to keeping you from complexity, using Astive means your application’s core is well tested and is being constantly improved. Here’s a quick list of features you’ll enjoy when using Astive:

* Multi-IVR applications
* Asterisk 1.8 or greater
* Compatible with Java 7 or greater
* Application-Server like operations(start, stop, undeploy, deploy...).
* Advanced API's for IVR creation
* Support for FastAGI (AMI on the way).
* Event-driven architecture
* Code generation
* Flexible licensing (http://en.wikipedia.org/wiki/Apache_License)
* Well documented.

Why do we use Java and Asterisk?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Asterisk, is without any doubts the most used open-source Telephony Engine in the world. It has a large community of developers, administrators and companies supporting it. With every version, they add a lot of new and exciting features and improvements.

In the other hand, Java has been consistently one of the favorite programming languages. With new languages adding to the  _JVM(Java Virtual Machine)_  – such as _Scala_, _Groovy_ and _JRuby_ – I believe we'll see _Java_ for many years.

Understanding the Basics
~~~~~~~~~~~~~~~~~~~~~~~~

There are some basic concepts that you need to know before you start developing voice applications with Astive. In this section, I'll describe how Astive functions in relation to Asterisk. I hope this help paint the hole picture.

Asterisk PBX
^^^^^^^^^^^^

As mentioned earlier, Asterisk is a Telephone Engine. It was developed originally as a PBX(Private Branch Exchange) by Mark Spencer of Digium, in 1999. Since then, a large community of developers has added to their core team.

Asterisk allows companies to place and receive calls coming from and to VoIP and PSTN networks. Calls can then be managed by voice applications such as IVRs, conference room, mailbox or sent to an agent. It also has multiple APIs to extend its functionalities. The two main APIs are AGI(Asterisk Gateway Interface) and AMI(Asterisk Manager Interface).

The AGI API
^^^^^^^^^^^

Asterisk Gateway Interface (AGI ) enables external applications to take control of an Asterisk channel. Astive supports FastAGI, a version of AGI, which allows applications to take control of a channel from another location of the network.

Reporting Issues
~~~~~~~~~~~~~~~~

The preferred place to report issues is with Astive is the Github issue tracker https://github.com/fonoster/astive/issues.
